version: '3'
services:
    db:
      image: mysql:5.7
      container_name: mysql
      ports:
        - 3306:3306
      environment:
        - LANG=C.UTF-8
        - TERM=dumb
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_DATABASE=BookDatabase
        - MYSQL_PASSWORD=password
        - MYSQL_USER=Book
      networks:
        - spring-boot-mysql-network

    backend:
      build:
        context: .
        dockerfile: Dockerfile
      container_name: backend
      restart: always
      ports:
        - 8080:8080
      depends_on:
        - db
      networks:
        - spring-boot-mysql-network
networks:
  spring-boot-mysql-network:
