spring:
  datasource:
    url: jdbc:mysql://db:3306/BookDatabase?useUnicode=true&characterEncoding=utf-8
    username: Book
    password: password
#    driver-class-name: com.mysql.cj.jdbc.Driver 会根据jdbc：mysql 自己找，可以省略
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
      use-new-id-generator-mappings: false
      ddl-auto: update
#server:
#  port: 8080 默认的端口，可以省略
